 name: Build and Deploy Backend-API
 on:
   push:
      branches:
        - main

 jobs:
    build-deploy:
      name: Backend-API
      runs-on: ubuntu-20.04
      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup jdk 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 17

        #- name: unit tests
        #  run: mvn -B test --file pom.xml
         
        #- name: build the app
        #  run: |
        #    mvn clean install -DskipTests
        #    mvn -B package --file pom.xml
            
        #- name: List target directory contents
        #  run: ls -la target/     

        - name: login to docker hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and Push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-spring-boot-app:v1.0.0   

             
