 name: build and deploy spring-api
 on:
   push:
      branches:
        - main

 jobs:
    build-deploy:
      name: build and deploy spring-api
      runs-on: ubuntu-20.04
      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup jdk 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 17

        - name: unit tests
          run: mvn -B test --file pom.xml

        - name: build the app
          run: |
            mvn clean install -DskipTests
            mvn -B package --file pom.xml

        - name: login to docker hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        # Build the Docker image
        - name: Build Docker image
          run: docker build -t my-spring-boot-app .

        - name: Tag Docker image
          run: | 
           docker tag my-spring-boot-app my-spring-boot-app:v1.0.0


    # Push the Docker image to Docker Hub
        - name: Push Docker image
          run: docker push my-spring-boot-app:v1.0.0
